name: Haskell CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-configure --enable-tests --enable-benchmarks
        cabal v2-build --only-dependencies
    - name: Build
      run: cabal v2-build
    - name: Run tests
      run: cabal v2-run unittest
